{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GglLfr.EntityAnno",
    "module": "entity",
    "version": "v2.5.0+v160",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "entity-v2.5.0+v160.jar",
          "url": "entity-v2.5.0+v160.jar",
          "size": 75255,
          "sha512": "0ac6c34adcab0e8445b4857f76e921bb35ada0040fcb346c62fb069bedc9a15e624a3b1ba6c83d978f28408772d6aae326f3154ed9c1f033164eab03b7b10dbc",
          "sha256": "1545ba9cc4024470f862df76c0cea3192c50a7cc91f7c3a2e2b596f5264ed6e4",
          "sha1": "a31eecc40d50503d592cd1d51320646ab595f2ed",
          "md5": "2fabfa4a29bf5d83eef58a1aac9758f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "Anuken",
          "module": "Mindustry",
          "version": {
            "requires": "v160.5"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "entity-v2.5.0+v160.jar",
          "url": "entity-v2.5.0+v160.jar",
          "size": 75255,
          "sha512": "0ac6c34adcab0e8445b4857f76e921bb35ada0040fcb346c62fb069bedc9a15e624a3b1ba6c83d978f28408772d6aae326f3154ed9c1f033164eab03b7b10dbc",
          "sha256": "1545ba9cc4024470f862df76c0cea3192c50a7cc91f7c3a2e2b596f5264ed6e4",
          "sha1": "a31eecc40d50503d592cd1d51320646ab595f2ed",
          "md5": "2fabfa4a29bf5d83eef58a1aac9758f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-v2.5.0+v160-javadoc.jar",
          "url": "entity-v2.5.0+v160-javadoc.jar",
          "size": 4253366,
          "sha512": "6289e353c356bb47926614ca8362c54a43610024d067ebf528f1ad2c2e2db0d504dd52937e73fcaf1485986894fcf7f831490438f6e8c0a9a509cc61bd5eb2da",
          "sha256": "d5b49bdb78267e214a4afa50e781dfdeeaba993634ed2f01a054d3c7251c5bc6",
          "sha1": "7af5388128e78f5ff48720a0601734d4a9b2d8f5",
          "md5": "664fa2ccad2c55e3275c9dcefb1fb5cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-v2.5.0+v160-sources.jar",
          "url": "entity-v2.5.0+v160-sources.jar",
          "size": 25329,
          "sha512": "b9595e7763397640099dea04d09ba1f6d59e7e676feea38e16d854223450b33dabb6300a9a9fdc45e94759b2d3e52f6942d0397f1144b0718299cf8fa4b6a882",
          "sha256": "8cafc8ca16d0a50c1647a182a66b1c5224dea97ac985af2d143d26d795908a8f",
          "sha1": "7d0d42fcd1bc7847a49f0eadaf25774e7ecefbfd",
          "md5": "c912b052bb337ade3f1072bf08391b53"
        }
      ]
    }
  ]
}
