{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GglLfr",
    "module": "EntityAnno",
    "version": "v2.1.0+v160",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "EntityAnno-v2.1.0+v160.jar",
          "url": "EntityAnno-v2.1.0+v160.jar",
          "size": 7904,
          "sha512": "5bb9eccf07e3185c8720e09dde4b2b4f5a5c0aa8d4c3b07a59ac4e17e9f0809718f7fc8bf1f67ceede6373219ce9c6ebff0dd02566a3fc8e06df41c05807a2ba",
          "sha256": "7eaca095501a291358ffad7a528774c9348085aa453dea5d7950f05b3c29b3b9",
          "sha1": "22c16db4678d6c66dbe5fe1115bccaf7267f6126",
          "md5": "63546a0ed6a71cc962e249011bdc69a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "Anuken",
          "module": "Mindustry",
          "version": {
            "requires": "v160.4"
          }
        }
      ],
      "files": [
        {
          "name": "EntityAnno-v2.1.0+v160.jar",
          "url": "EntityAnno-v2.1.0+v160.jar",
          "size": 7904,
          "sha512": "5bb9eccf07e3185c8720e09dde4b2b4f5a5c0aa8d4c3b07a59ac4e17e9f0809718f7fc8bf1f67ceede6373219ce9c6ebff0dd02566a3fc8e06df41c05807a2ba",
          "sha256": "7eaca095501a291358ffad7a528774c9348085aa453dea5d7950f05b3c29b3b9",
          "sha1": "22c16db4678d6c66dbe5fe1115bccaf7267f6126",
          "md5": "63546a0ed6a71cc962e249011bdc69a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-v2.1.0+v160-javadoc.jar",
          "url": "EntityAnno-v2.1.0+v160-javadoc.jar",
          "size": 83192,
          "sha512": "f9a6bdd108893a8bc3880c2eba2135afe01b25b5c41393575da69c40e1da21bc14d40bdbbe93a868030c4d1dde9d96068502fcdeca67bf6c12290d540ca29057",
          "sha256": "5c529eee4cee86c3f76e01f33993d1479485309d505d229a8ce8e2d7a05f7f4b",
          "sha1": "7cd321ccca013d056596040199f3d3d12b1669dc",
          "md5": "71fdd0028885ab7cb0aa780f871b2a48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-v2.1.0+v160-sources.jar",
          "url": "EntityAnno-v2.1.0+v160-sources.jar",
          "size": 3215,
          "sha512": "5c331ba0c9ed863f20c53b5744297e31bce9fc36115cadb5ac94cbbaeebd967fa26206381d5db7081320681b2fd6c9dfd8a67444b1eb0cc42d41c9c26c997abf",
          "sha256": "ad7d2ede1aeb91ff76d872f65906284c9c4e2cfbeb8ef3c2c331e0e53f78f607",
          "sha1": "d34cd3b82f9cb2e7bef1dd5d4a21207fdcc8eff8",
          "md5": "4163180a06fc65c972de87c1aa9b6a14"
        }
      ]
    }
  ]
}
