{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GglLfr.EntityAnno",
    "module": "entity",
    "version": "v2.2.1+v160",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "entity-v2.2.1+v160.jar",
          "url": "entity-v2.2.1+v160.jar",
          "size": 75179,
          "sha512": "f7f2e9a80b83d912e3795577c7aaa82e8924282d9b1f9eeb96c213fb8cfef061c4139fc18f81151fb969407d5038c0b30a4f99c87a1e8c6e713203140900ddb5",
          "sha256": "c0cf6b67dff570f75e22fd130b1703f42ad48c42c0516df1f3792b5ad6b0cfec",
          "sha1": "c7e04cbea33261e7b26567ddccd01dca52671d66",
          "md5": "1482a38ab1c3b39bdfea2332b27145e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "Anuken",
          "module": "Mindustry",
          "version": {
            "requires": "v160.5"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "entity-v2.2.1+v160.jar",
          "url": "entity-v2.2.1+v160.jar",
          "size": 75179,
          "sha512": "f7f2e9a80b83d912e3795577c7aaa82e8924282d9b1f9eeb96c213fb8cfef061c4139fc18f81151fb969407d5038c0b30a4f99c87a1e8c6e713203140900ddb5",
          "sha256": "c0cf6b67dff570f75e22fd130b1703f42ad48c42c0516df1f3792b5ad6b0cfec",
          "sha1": "c7e04cbea33261e7b26567ddccd01dca52671d66",
          "md5": "1482a38ab1c3b39bdfea2332b27145e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-v2.2.1+v160-javadoc.jar",
          "url": "entity-v2.2.1+v160-javadoc.jar",
          "size": 176884,
          "sha512": "3626f954be32b7d6d9a5c78387cbbb53d1eccc42cf3861ee75980b745f08b698717730a4eaf2e8d9fdd52da62565d4ad0dfb666f37d6ceadbf66270d86d58ba8",
          "sha256": "097af482ea091ac7716edf1719e7cd7cdaaf6786bb95f29c658ed9b46cffc34d",
          "sha1": "314a3069da01c74eea7e8a5bfaedd8ab9e1c9f1e",
          "md5": "93091331ecee4337dc05963bdebf6356"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-v2.2.1+v160-sources.jar",
          "url": "entity-v2.2.1+v160-sources.jar",
          "size": 25322,
          "sha512": "52d97fee42d6d678e15c99061fea60fa2eb1493119526b202a89e0964d5f5756a0dc90c84f1992fd62ad112773bcc98e19c1ed022845a531b2c65b9bd39cda3f",
          "sha256": "b2437ff40a423c12bdb07262298fba5efcaeda8caf14aa2782aaf43e2feb6290",
          "sha1": "b5ecf004858108ffa7bc735bef19c2785176fd6c",
          "md5": "8736cb66c1cd4d88ad77c5d32e174703"
        }
      ]
    }
  ]
}
