{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GglLfr.EntityAnno",
    "module": "entity",
    "version": "43d19e66ea",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "entity-43d19e66ea.jar",
          "url": "entity-43d19e66ea.jar",
          "size": 68628,
          "sha512": "1e37dfa4aebe50a3e9bab04111c50d2e2e3c828eab08f67d5b08383b6b9ebcee13edcb8394a1ac242e5392f068a23aeb730412b6c5118bd6bd525e17e0863e7a",
          "sha256": "3284650a1316fa379f046986318535b2f2bdc67173f8c0826dbce0c6d20537b0",
          "sha1": "d4d159e3e0d32bc8a37d20d7e5b30744af6413e9",
          "md5": "f5f413dca2640a9ec851e64908753207"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v158"
          }
        },
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v158"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "entity-43d19e66ea.jar",
          "url": "entity-43d19e66ea.jar",
          "size": 68628,
          "sha512": "1e37dfa4aebe50a3e9bab04111c50d2e2e3c828eab08f67d5b08383b6b9ebcee13edcb8394a1ac242e5392f068a23aeb730412b6c5118bd6bd525e17e0863e7a",
          "sha256": "3284650a1316fa379f046986318535b2f2bdc67173f8c0826dbce0c6d20537b0",
          "sha1": "d4d159e3e0d32bc8a37d20d7e5b30744af6413e9",
          "md5": "f5f413dca2640a9ec851e64908753207"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-43d19e66ea-javadoc.jar",
          "url": "entity-43d19e66ea-javadoc.jar",
          "size": 165801,
          "sha512": "a0dc43f1b63a1dca3ea0ee72e9145aea265d38f6c67b427f00b97872572d215be772c55950b47bf895e48031e1084e16f3c40a6e8391ff0931148abd31f45913",
          "sha256": "99acaeb6eb902010479a02b6af76d8230e53ce29f07aa2fd0592bdcc1c1e6571",
          "sha1": "20cc2512dacd572659a584a9696f3f017ca452f8",
          "md5": "98e582dc500c410082e89ab29be176f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-43d19e66ea-sources.jar",
          "url": "entity-43d19e66ea-sources.jar",
          "size": 22800,
          "sha512": "a9e40b1f0eda73d92b1eeb39ddcb6de7350ad9a7c5ba6b3e6b33a597926f89a6209a7eb88317094fa3717652c25e1f1b7d7ac38014e291de7812c9e4a390c961",
          "sha256": "9b26404ea27cf97c0e4596ad89293ef90f9fc16c4fcf3a3bc60279b96d8fc201",
          "sha1": "5d4c3471a88cadd7c9839167f94699aaee596f08",
          "md5": "a442418dd8b763d6f95d4acab0eb6320"
        }
      ]
    }
  ]
}
