{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GlennFolker.EntityAnno",
    "module": "entity",
    "version": "a01f25c367",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "entity-a01f25c367.jar",
          "url": "entity-a01f25c367.jar",
          "size": 67747,
          "sha512": "6ca37c248b94c5f2384a4461e465822f51129a3314bdaa3e1c97bf4174581fe6284447c80fe4f3d6a0be0b5c18d7120ffc872309b8b28d517f16a80dc5847145",
          "sha256": "045231f58a2bd0e9b7563dbcf1ff7bbc8f31946bf04ee6741ea36c6c459d9d64",
          "sha1": "2e1314c1c280daf610d215abb09ab2b51c9ff138",
          "md5": "2754c525b8ea3828bb0c93ca7ad96474"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "entity-a01f25c367.jar",
          "url": "entity-a01f25c367.jar",
          "size": 67747,
          "sha512": "6ca37c248b94c5f2384a4461e465822f51129a3314bdaa3e1c97bf4174581fe6284447c80fe4f3d6a0be0b5c18d7120ffc872309b8b28d517f16a80dc5847145",
          "sha256": "045231f58a2bd0e9b7563dbcf1ff7bbc8f31946bf04ee6741ea36c6c459d9d64",
          "sha1": "2e1314c1c280daf610d215abb09ab2b51c9ff138",
          "md5": "2754c525b8ea3828bb0c93ca7ad96474"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-a01f25c367-javadoc.jar",
          "url": "entity-a01f25c367-javadoc.jar",
          "size": 164265,
          "sha512": "cc955501e14a5643982e62349c67800c6952310b98411e22bb2fba99c196d3158502593e2f6e494db303a4cd35d31fb5cdc5de1f03a757dff7e78f8564fa1a7e",
          "sha256": "45f59681d247636b4a45952696ef50686bfb1c4c65c481d6582ac8f599af87a5",
          "sha1": "9495b129594337c61a2ab88ca0bf9618a678fccc",
          "md5": "304f02d0bbf385282a72b262ca3840fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-a01f25c367-sources.jar",
          "url": "entity-a01f25c367-sources.jar",
          "size": 22616,
          "sha512": "77d60a93b412c0f1cff37f029cdb8a3ef173c77477ec94c720e21c46bb023643c809fd00cc7359a4886d62a92c381064cdc8b03278a44449e450e9a8a66b1d9f",
          "sha256": "4b52f96b4e6fa21c8d1f7600c84cd2c9abe059e699c7dc35361e3d6636ddccb1",
          "sha1": "8fbcec5002b70ca15f851440f1b79483e97701c7",
          "md5": "b4f7c54ac9f59cb852de0de54e71a5ab"
        }
      ]
    }
  ]
}
