{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GlennFolker",
    "module": "EntityAnno",
    "version": "4fa97fdef8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "EntityAnno-4fa97fdef8.jar",
          "url": "EntityAnno-4fa97fdef8.jar",
          "size": 8362,
          "sha512": "86ba2db5dfe088cd8cefb53233cda22dca2a4e378a5f817eedd08089412b0927a454133002b379932c073909371174a9156cdd5c8eb3e1b3fc160f43c951bbf1",
          "sha256": "3335a08f383ceb0c223692b9b401be0193575b90f0732361796744b66152591f",
          "sha1": "c74d07a2d75714b910bbdfb75b8077c930255852",
          "md5": "cf6de452fe37880aad3e426031a0a613"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.kapt",
          "module": "org.jetbrains.kotlin.kapt.gradle.plugin",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "EntityAnno-4fa97fdef8.jar",
          "url": "EntityAnno-4fa97fdef8.jar",
          "size": 8362,
          "sha512": "86ba2db5dfe088cd8cefb53233cda22dca2a4e378a5f817eedd08089412b0927a454133002b379932c073909371174a9156cdd5c8eb3e1b3fc160f43c951bbf1",
          "sha256": "3335a08f383ceb0c223692b9b401be0193575b90f0732361796744b66152591f",
          "sha1": "c74d07a2d75714b910bbdfb75b8077c930255852",
          "md5": "cf6de452fe37880aad3e426031a0a613"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-4fa97fdef8-javadoc.jar",
          "url": "EntityAnno-4fa97fdef8-javadoc.jar",
          "size": 85110,
          "sha512": "dbbd5aee7f6c3d47271ac16175469d0bb2f85c6279cfb26a33110731fbc3980c5f22245c3d824e350a7f9a9050bfedd5746962cc3f066bef66ca5e3854df5f57",
          "sha256": "cf4a37fc1c137282075efd989452d2f60c18c99895635ef766bb6861b23514d2",
          "sha1": "887f1c31843a1044570ed1fecf41e017cbb97c12",
          "md5": "9d69d3da1e6e3989dd006427695591a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-4fa97fdef8-sources.jar",
          "url": "EntityAnno-4fa97fdef8-sources.jar",
          "size": 3492,
          "sha512": "97ef5099e38b780aeb91444a5b443465af02efff39d8736d479810ffbb36692be2cc56e2f3f7489c372dd28181bcc5eb40fe1e99653e82b00797cae061cd27e7",
          "sha256": "c6dbd4465855cb3de14c9c2581cd8bcf8ee4233e44afafc13c91a10103a32461",
          "sha1": "40b029baffcbb07a74cf6d9e374a3d40c1438dad",
          "md5": "eaf8e8537b2b77fcdce9832d6e525414"
        }
      ]
    }
  ]
}
