{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GlennFolker.EntityAnno",
    "module": "entity",
    "version": "3c4deb3ec2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "entity-3c4deb3ec2.jar",
          "url": "entity-3c4deb3ec2.jar",
          "size": 67747,
          "sha512": "69361ccbe73e63bbde52825a295be164cf359a495443c955c41d72e3b4959efbc10f7d0dfeb9c4ac4f6ee936ff7dcb66c03b4d87cb2d8ce6ce1b58ca035dd00f",
          "sha256": "ed6dbbb9c82fca9f2a84c2d2af07c022bbdd6d77aed7f311ef93e339ff2778c8",
          "sha1": "f576aa5490b54979c50acd185b390f729052f1a0",
          "md5": "7e4034e570237c73ba56e24c89078efa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "entity-3c4deb3ec2.jar",
          "url": "entity-3c4deb3ec2.jar",
          "size": 67747,
          "sha512": "69361ccbe73e63bbde52825a295be164cf359a495443c955c41d72e3b4959efbc10f7d0dfeb9c4ac4f6ee936ff7dcb66c03b4d87cb2d8ce6ce1b58ca035dd00f",
          "sha256": "ed6dbbb9c82fca9f2a84c2d2af07c022bbdd6d77aed7f311ef93e339ff2778c8",
          "sha1": "f576aa5490b54979c50acd185b390f729052f1a0",
          "md5": "7e4034e570237c73ba56e24c89078efa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-3c4deb3ec2-javadoc.jar",
          "url": "entity-3c4deb3ec2-javadoc.jar",
          "size": 164169,
          "sha512": "0d2409f178b0ac7fecea4e7f16e728feb4e9c4c321bc7395907d5eb3404f1e2d7615bcc28baece7390874919bb1341800bf797593877fa7f47087d3a2e680dae",
          "sha256": "09322bcc032279b63c7a5829a4a33f651fa25eefb46f6e0aa5063c0797571266",
          "sha1": "bc7cffe76d7cc1812b31f391ac64f626128cb773",
          "md5": "605ca4c443453d47db1fd728c5d055b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-3c4deb3ec2-sources.jar",
          "url": "entity-3c4deb3ec2-sources.jar",
          "size": 22616,
          "sha512": "b14560db1fc32073ddeffc26a0a7319dc580eb98e86f3e1e011ac0cbf243ebca627a47b69b1c027abbc57c35d02c9d4986860166beea08cdfa08821dc85f7e9b",
          "sha256": "628cd8454d729f4fcd3e563c0aeba6edc7acaa6dd86f6f689089d5181364646b",
          "sha1": "3268bea20f2c852d15e7b4f13a4bc1895acbd7a9",
          "md5": "278b13efce31f6fb3e22370cb8163b52"
        }
      ]
    }
  ]
}
