{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GlennFolker.EntityAnno",
    "module": "entity",
    "version": "4fa97fdef8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "entity-4fa97fdef8.jar",
          "url": "entity-4fa97fdef8.jar",
          "size": 67747,
          "sha512": "89b15d6fe08a4e913d7de5b756a8b40acc8dbedc69dcdbca8e65b1e5b13b3b3b20281fd27e9426d3a326c522a570f912aaf61078ecc11e0bd28827092ad3e0f9",
          "sha256": "71a0ef5afc0201b9347b853097e24b33099efc782487d0560ec0074b1bf0922d",
          "sha1": "dca69c7d122f94deba112a4291364bb6f6d7ff19",
          "md5": "e04a180b9cdf02d51253873a61239d13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "entity-4fa97fdef8.jar",
          "url": "entity-4fa97fdef8.jar",
          "size": 67747,
          "sha512": "89b15d6fe08a4e913d7de5b756a8b40acc8dbedc69dcdbca8e65b1e5b13b3b3b20281fd27e9426d3a326c522a570f912aaf61078ecc11e0bd28827092ad3e0f9",
          "sha256": "71a0ef5afc0201b9347b853097e24b33099efc782487d0560ec0074b1bf0922d",
          "sha1": "dca69c7d122f94deba112a4291364bb6f6d7ff19",
          "md5": "e04a180b9cdf02d51253873a61239d13"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-4fa97fdef8-javadoc.jar",
          "url": "entity-4fa97fdef8-javadoc.jar",
          "size": 164208,
          "sha512": "62abc3a0fa06a81f926f7113dc2bcabfe3beed6ed4b7e67d1f6534520a5a36fc4150dd2c37f094b99813c882cd8ecded05eefbd4b1e429df016577567f9ee649",
          "sha256": "961bb3e3689d0fc01f6c384213db0e56b154280e92f79d21250fca119347ba03",
          "sha1": "4a46b5bcd9b7386df342ec37bb377f6ec7de73ac",
          "md5": "ef2db52079001285ea68d8fcc093083f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-4fa97fdef8-sources.jar",
          "url": "entity-4fa97fdef8-sources.jar",
          "size": 22616,
          "sha512": "6ba07fe9f784d569d15e960f681019daf4156a9569f326b4b19dd06a6d11019bd2b74ae1e8887cefda6c7699150710fd1075907fb5c73d76ca68570d79224fb0",
          "sha256": "ce78f73214e575a06fc6b87f2b2ae718ea732d8742746df8dfc1cc9f1a6e533b",
          "sha1": "9633c1984d4c76d1d919b197f8b984f825493aed",
          "md5": "50e1ad6a533f9e4f39dc63311e76985b"
        }
      ]
    }
  ]
}
