{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GglLfr.EntityAnno",
    "module": "entity",
    "version": "dc39b86cf0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "entity-dc39b86cf0.jar",
          "url": "entity-dc39b86cf0.jar",
          "size": 68314,
          "sha512": "2d4ed8674973d2ccb6047dfbe9db74d4f2f16c331147f61181fd361a9941b3dd56abe4728002c6cdfe978cda52fa77df5763ec043f2333b1b4532afbaa0a4f1e",
          "sha256": "1b1336c91ebff44ddd9dcb1eefcefe68cdde12ebb087a803509137c7924a7cbd",
          "sha1": "b041fc5cf18eef2eb4d11af1bc9220883a898b62",
          "md5": "ff1cf8466eb6eb01a9b0cf69b0c42a44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v158"
          }
        },
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v158"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "entity-dc39b86cf0.jar",
          "url": "entity-dc39b86cf0.jar",
          "size": 68314,
          "sha512": "2d4ed8674973d2ccb6047dfbe9db74d4f2f16c331147f61181fd361a9941b3dd56abe4728002c6cdfe978cda52fa77df5763ec043f2333b1b4532afbaa0a4f1e",
          "sha256": "1b1336c91ebff44ddd9dcb1eefcefe68cdde12ebb087a803509137c7924a7cbd",
          "sha1": "b041fc5cf18eef2eb4d11af1bc9220883a898b62",
          "md5": "ff1cf8466eb6eb01a9b0cf69b0c42a44"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-dc39b86cf0-javadoc.jar",
          "url": "entity-dc39b86cf0-javadoc.jar",
          "size": 165719,
          "sha512": "5a57521ba54d178869793aa52b3c9e56e963c31d2cbf5d09d13ccb8d72c221346bc2f25e3bbcf89d52013efcc5637693bd28bc38e4edfe7346bfb55802140c8f",
          "sha256": "8a01ebbfd4ec09fe051f276c36acc5462ca9f2cb0df2b817cd8d497c2496e24e",
          "sha1": "3d6de772b48e5efe8d182a266b92b5be30fd5fb6",
          "md5": "e73f87fcf6532893dcfcf41e72f664e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-dc39b86cf0-sources.jar",
          "url": "entity-dc39b86cf0-sources.jar",
          "size": 22665,
          "sha512": "3429b4e29cea055212845b8f5e5711e12c3f80c9a567f819ddcef00ad5540ea0c8ca7c73da84a1b6e764a0d64ddf9385467a03b53acca6321a64cbf33368006c",
          "sha256": "e3d8f205c06df5f1ec97c3919315d6d226c4a865b345b7f2ff88fd0e68b22e31",
          "sha1": "46aafaf9d4004c665b7acb03ca9a7fb86817b4d9",
          "md5": "4956208232e2bdb4b4a6e12d62d8fc45"
        }
      ]
    }
  ]
}
