{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GglLfr",
    "module": "EntityAnno",
    "version": "dc39b86cf0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "EntityAnno-dc39b86cf0.jar",
          "url": "EntityAnno-dc39b86cf0.jar",
          "size": 8427,
          "sha512": "7d1098e65ba9e903ec9c42b091b697eac20d06b143a7d13ef3a1e7b1eb0a39f043474f226d6413ff7a4b5a56872d7b189a436e441e3848df05988c18777d35cf",
          "sha256": "a4a29e54b46a315596d1a63e679c6c383a7978665dd9cdc6d233cf270abbbc19",
          "sha1": "4c030279f59945df9e991ca5bb6ee414dcc850bc",
          "md5": "dba6a9b3d384fc597b7f618d60d79516"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v158"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.kapt",
          "module": "org.jetbrains.kotlin.kapt.gradle.plugin",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "EntityAnno-dc39b86cf0.jar",
          "url": "EntityAnno-dc39b86cf0.jar",
          "size": 8427,
          "sha512": "7d1098e65ba9e903ec9c42b091b697eac20d06b143a7d13ef3a1e7b1eb0a39f043474f226d6413ff7a4b5a56872d7b189a436e441e3848df05988c18777d35cf",
          "sha256": "a4a29e54b46a315596d1a63e679c6c383a7978665dd9cdc6d233cf270abbbc19",
          "sha1": "4c030279f59945df9e991ca5bb6ee414dcc850bc",
          "md5": "dba6a9b3d384fc597b7f618d60d79516"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-dc39b86cf0-javadoc.jar",
          "url": "EntityAnno-dc39b86cf0-javadoc.jar",
          "size": 84986,
          "sha512": "a887ec4f36bf8aee4467469e8f506153d84e4eb7ecb65861c6b534c13276162b01cdce3588796ce20eb6e78f52b1994b59ead8e79d79482b8e1b94afb205a73a",
          "sha256": "d6206ceea3f09d5864ff6dc83772f0a8117d5498f0c73bf85056682698276d6f",
          "sha1": "7f4d968b61ade12c890b5fe8d5ce0aa4c61da830",
          "md5": "810e3d20cfc947ef7f1652f6f0c33530"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-dc39b86cf0-sources.jar",
          "url": "EntityAnno-dc39b86cf0-sources.jar",
          "size": 3520,
          "sha512": "7952e68ed7a7818aef8ad71a5c44f7c6d832e142cf10b56fb0acb598ffe3cddcf5a91e36e7c424b50a9d8497ed850f81d3369dbf04084dc9590bfb8eece5f930",
          "sha256": "acaeb8d91eb066317223cdca5206db361497d29a1432792f7c28828dbae8867d",
          "sha1": "c625d591060fa6977e8ad976db738cf4dd6a2eee",
          "md5": "16deb2a73391299a103e5d7a3880d5d7"
        }
      ]
    }
  ]
}
