{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GlennFolker.EntityAnno",
    "module": "downgrader",
    "version": "7131b57842",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "downgrader-7131b57842.jar",
          "url": "downgrader-7131b57842.jar",
          "size": 2692,
          "sha512": "ea3e1c2374e33090a62f460e1c358523829bae1fd0bbfbab040f4a45783bdeb0c017b167e48ff1a177d9a27db9114995ba15115cda4f507cb9438804a0840e50",
          "sha256": "10b47e1c32554d1ada280f2133593f0fea4aedcb636eb7b166a74495549aa4e2",
          "sha1": "6fcd8102fac870f461e2c45ab5892d5cb9f87712",
          "md5": "df60ead904b1b7709e712011c50ff597"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        }
      ],
      "files": [
        {
          "name": "downgrader-7131b57842.jar",
          "url": "downgrader-7131b57842.jar",
          "size": 2692,
          "sha512": "ea3e1c2374e33090a62f460e1c358523829bae1fd0bbfbab040f4a45783bdeb0c017b167e48ff1a177d9a27db9114995ba15115cda4f507cb9438804a0840e50",
          "sha256": "10b47e1c32554d1ada280f2133593f0fea4aedcb636eb7b166a74495549aa4e2",
          "sha1": "6fcd8102fac870f461e2c45ab5892d5cb9f87712",
          "md5": "df60ead904b1b7709e712011c50ff597"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "downgrader-7131b57842-javadoc.jar",
          "url": "downgrader-7131b57842-javadoc.jar",
          "size": 80976,
          "sha512": "8994434d6dd5dfac26d1761d0c4c023345d39f60de78cf58df089be9bdcffc080a4232a78eb02064bc97845c64d6897c66459e74cf9ca51da0e150fd04faf50e",
          "sha256": "6e29d670505cbd51060c031fb19f4c2bc96bf01903a9961a2c3e62fa63048da5",
          "sha1": "399f2d670f06734c1586610ffa88db34af87ee0a",
          "md5": "95338d043cb43a0e9fe65136c791c728"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "downgrader-7131b57842-sources.jar",
          "url": "downgrader-7131b57842-sources.jar",
          "size": 2103,
          "sha512": "35e6f3113e9bba66695fe0aa46cdf518c9a42c3546bce545b9b1a22ae8275936b8838b617af68dd410a89c6b69bc4bac968d39be363bc4dfac6019d274005d0d",
          "sha256": "003ae6ada544191dd8574fdb383d369e325e9840357735b1e85b230a69345835",
          "sha1": "694fe62b4a25d5fae5abb63dea47a8eb9d33c535",
          "md5": "315596b530c9ed9949b6f289c66e166c"
        }
      ]
    }
  ]
}
