{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GlennFolker.EntityAnno",
    "module": "entity",
    "version": "284472e6f1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "entity-284472e6f1.jar",
          "url": "entity-284472e6f1.jar",
          "size": 67747,
          "sha512": "2af863a682abf19fd9ad575e1a2fcf4f5cadd1d5dd108a91eeb3d496aff860fa7ef25bb4ab62ad752462569ea565b3894c6cebf71d10a65beb3b2b3670bf8248",
          "sha256": "8c1237a9a8adc879fa652b306d1f710a707741c2ef8fc633bf54b01362c9d0b9",
          "sha1": "02d6e6a0ef9f17ae71ef74d9c7c832bcd9d960bb",
          "md5": "1e68da799f3e8be8931332ce08556ec5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "entity-284472e6f1.jar",
          "url": "entity-284472e6f1.jar",
          "size": 67747,
          "sha512": "2af863a682abf19fd9ad575e1a2fcf4f5cadd1d5dd108a91eeb3d496aff860fa7ef25bb4ab62ad752462569ea565b3894c6cebf71d10a65beb3b2b3670bf8248",
          "sha256": "8c1237a9a8adc879fa652b306d1f710a707741c2ef8fc633bf54b01362c9d0b9",
          "sha1": "02d6e6a0ef9f17ae71ef74d9c7c832bcd9d960bb",
          "md5": "1e68da799f3e8be8931332ce08556ec5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-284472e6f1-javadoc.jar",
          "url": "entity-284472e6f1-javadoc.jar",
          "size": 164265,
          "sha512": "d043b46b5af736d1f7f3763b7db02d0c97cf54edaed13959a47f740bd541b39808725e8b0860f9c32d0fbf8ed8de6004c8c475bf3b3daa1e6450d64887c58f53",
          "sha256": "21f8a5ee3d449f83db683455a9a6c23d0d10c0543eef2a871e4868f40b3eb12e",
          "sha1": "2c4e27b403dcbf32ffe4c877b5e28bf5b948f777",
          "md5": "4b1af4eb8181276e2bcf893c2a6d1015"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-284472e6f1-sources.jar",
          "url": "entity-284472e6f1-sources.jar",
          "size": 22616,
          "sha512": "0b0656a8ca17fbab569fdf0c98baf4fa4d280e65f58f5542707f43abcad068bbb57ca55dbc2bf1adc0cd431491fa33e69bfe72ca36ac18cdc9b0bc0dc0d1b41c",
          "sha256": "75fe0f3af7558499f82ff040d17f9aaf60ecfc86e56694c9e53d9ccd0a685e72",
          "sha1": "7b0e3830cc29f747362b91ed53641cd15d761af5",
          "md5": "aa41d63e3baa9e14478eb8b4deef0e12"
        }
      ]
    }
  ]
}
