{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GlennFolker",
    "module": "EntityAnno",
    "version": "284472e6f1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "EntityAnno-284472e6f1.jar",
          "url": "EntityAnno-284472e6f1.jar",
          "size": 8362,
          "sha512": "2dfe42ad635af3ce37119bd60d473f3a5eb40a18c310c301f4c612d87a1bd6a7476b217a632469479ce20e08a823e585915240b42a3b0feeb461bb0bdaedefec",
          "sha256": "e26e79e73bc72d3a0f7d50f770af44a2040f7cd4924c62861b473e7770a2e323",
          "sha1": "6f0b959f99c34e5846d6ccc2eec3789f80fab76b",
          "md5": "85f4b231ba3a983a6906df897d2f6366"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.kapt",
          "module": "org.jetbrains.kotlin.kapt.gradle.plugin",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "EntityAnno-284472e6f1.jar",
          "url": "EntityAnno-284472e6f1.jar",
          "size": 8362,
          "sha512": "2dfe42ad635af3ce37119bd60d473f3a5eb40a18c310c301f4c612d87a1bd6a7476b217a632469479ce20e08a823e585915240b42a3b0feeb461bb0bdaedefec",
          "sha256": "e26e79e73bc72d3a0f7d50f770af44a2040f7cd4924c62861b473e7770a2e323",
          "sha1": "6f0b959f99c34e5846d6ccc2eec3789f80fab76b",
          "md5": "85f4b231ba3a983a6906df897d2f6366"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-284472e6f1-javadoc.jar",
          "url": "EntityAnno-284472e6f1-javadoc.jar",
          "size": 85122,
          "sha512": "f527ba4682bd40d2099f8fefdbe04105de9b468b163c9b14d9fbae68c16b14ee9ed0d3805aa5d2152c934a42a3b6e90369686ef28f5af7305fcc04faad1a28cc",
          "sha256": "9e01696239a15953a13926f318cc731c6e84f332d5e63b7c64c64945b161030c",
          "sha1": "a7f0934e1750bbaaf405ce405b938091ea8db155",
          "md5": "8f6f5491206442d5ccbfcb546e974bae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-284472e6f1-sources.jar",
          "url": "EntityAnno-284472e6f1-sources.jar",
          "size": 3492,
          "sha512": "343413c78d15d4c023ce9ea2ee20d4754cf01a514b03ed10ad37b5f184d05baf3a88e591b83104e7eb29308caef1f5ecade7b3df1d5d62884e83f9a2cec6cfa7",
          "sha256": "89496b68ae21bfe0564e960b07f2d50361373a79888749740372e89756b1be67",
          "sha1": "a96334a277c88e88a225d687e35a3583d244e01f",
          "md5": "d4557d97d1a37594514073c9b63b1cb5"
        }
      ]
    }
  ]
}
