{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GlennFolker",
    "module": "EntityAnno",
    "version": "3c4deb3ec2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "EntityAnno-3c4deb3ec2.jar",
          "url": "EntityAnno-3c4deb3ec2.jar",
          "size": 8362,
          "sha512": "f9d7cf37e45ed86117a1e0a0337ff281e4d3e51a84f66f9f1dbc5ed0b53d4d4f4e175a7110c24b149d2f93a6c8a1e71dfcc70107c188446b4591918b9001ccbf",
          "sha256": "7059bf55b9bb95ee82ea55dc7a186688d5c2fd4901a6ec1e3d05f7bebfe53ea7",
          "sha1": "1a6374f3c8f0812392ad11a08e219db96f877559",
          "md5": "16e9d7d15a8f4b548bae20c0ce26f14f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.kapt",
          "module": "org.jetbrains.kotlin.kapt.gradle.plugin",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "EntityAnno-3c4deb3ec2.jar",
          "url": "EntityAnno-3c4deb3ec2.jar",
          "size": 8362,
          "sha512": "f9d7cf37e45ed86117a1e0a0337ff281e4d3e51a84f66f9f1dbc5ed0b53d4d4f4e175a7110c24b149d2f93a6c8a1e71dfcc70107c188446b4591918b9001ccbf",
          "sha256": "7059bf55b9bb95ee82ea55dc7a186688d5c2fd4901a6ec1e3d05f7bebfe53ea7",
          "sha1": "1a6374f3c8f0812392ad11a08e219db96f877559",
          "md5": "16e9d7d15a8f4b548bae20c0ce26f14f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-3c4deb3ec2-javadoc.jar",
          "url": "EntityAnno-3c4deb3ec2-javadoc.jar",
          "size": 85097,
          "sha512": "5c37fa6fa9f6d6157a4becfb7259366a21fa764ddd85961d7ce4bbf7f5a258b7454240674922d18e782e355c667d9d7d8e64b41df87e396b08bcce7209313f1c",
          "sha256": "5c23889bcbee6a807414a51254ffe89712db31e2ae94ff7750b175a380cbb717",
          "sha1": "146a2bc62cfa0f218d3cb4c57d0039e897884951",
          "md5": "399ac7312a716947a2caa3efad073ead"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-3c4deb3ec2-sources.jar",
          "url": "EntityAnno-3c4deb3ec2-sources.jar",
          "size": 3492,
          "sha512": "235917d05e837af743cd9109b9719a4eef4c5024c30fd09b8ccce217578adc3f25e6e9b72fac258f0e48f84176c4f6bd05f6e88437d44ca26b868a5156f4bd1e",
          "sha256": "a74cb8a8135d3a04553d73e4ed8ff6f48adb7d34869426caaa11c83d09b32dc7",
          "sha1": "4d8e31d95188239abb7d3e77012fb9f312ade977",
          "md5": "5814db57a087489e954edcddf313c07f"
        }
      ]
    }
  ]
}
