{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GglLfr",
    "module": "EntityAnno",
    "version": "v159.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "EntityAnno-v159.7.3.jar",
          "url": "EntityAnno-v159.7.3.jar",
          "size": 8768,
          "sha512": "4d0c7abfe758703d2b7a467cd58996e212585e371a46ab1219e2e382adb46ba84c3746724cae6048285f4d3f77853a3ae632b3ecf0a981035a4d5a43529dc12b",
          "sha256": "7d864e479247b2afe49c18b6e2ae6b9c01f69e0c01b0cef5fa0dfb37815125f5",
          "sha1": "e7ffd152bbd10d54f772fbc7628ef2945c28e4ef",
          "md5": "704dda9e2bdf38cc54ed93fcfb2ae817"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v159.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin.kapt",
          "module": "org.jetbrains.kotlin.kapt.gradle.plugin",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "EntityAnno-v159.7.3.jar",
          "url": "EntityAnno-v159.7.3.jar",
          "size": 8768,
          "sha512": "4d0c7abfe758703d2b7a467cd58996e212585e371a46ab1219e2e382adb46ba84c3746724cae6048285f4d3f77853a3ae632b3ecf0a981035a4d5a43529dc12b",
          "sha256": "7d864e479247b2afe49c18b6e2ae6b9c01f69e0c01b0cef5fa0dfb37815125f5",
          "sha1": "e7ffd152bbd10d54f772fbc7628ef2945c28e4ef",
          "md5": "704dda9e2bdf38cc54ed93fcfb2ae817"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-v159.7.3-javadoc.jar",
          "url": "EntityAnno-v159.7.3-javadoc.jar",
          "size": 83152,
          "sha512": "d726df46cb4621fcee265bc3f5f45abb32d5477c95451e7b5adb4c289e9f9eaa8703dc3755996d178271a535957ffe1b3347c4a3441b84fde59c5cf1dee8f1c2",
          "sha256": "4c616da73b6a55df4f984e1d8008bf42de3f35fb630bbe618fdea61877b746ba",
          "sha1": "e75a426a3d0ed4a7d4219d515891c09573c81745",
          "md5": "aed2614a4ae40149acd415de132f8f1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "EntityAnno-v159.7.3-sources.jar",
          "url": "EntityAnno-v159.7.3-sources.jar",
          "size": 3553,
          "sha512": "2ce5d592477238ad28df4fa5428c4889dacee7be183f23ed66d707e8e7d501d8d333cd765b1db55918766072964c0404c6a99e7f5020fb043a1ff55f5bea295d",
          "sha256": "3b0ac220267d64889a9f33424ab3f1edccbc2c33a60f9ab09bc89ed0de36656f",
          "sha1": "1bd4e3865c1bf0e1f747560db2cbc53261a52f4f",
          "md5": "cbca766f81b2f51811285c7dd37e03d7"
        }
      ]
    }
  ]
}
