{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GglLfr.EntityAnno",
    "module": "entity",
    "version": "v159.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "entity-v159.7.1.jar",
          "url": "entity-v159.7.1.jar",
          "size": 69564,
          "sha512": "73bc18fdcc4380afd55232391968f99bb621a5db8e1d382c0c19fb8303943528b3ad971a4efd9e200fb8dd0152545e994ad5a8a22b4693022a6ef4b665fc6001",
          "sha256": "3a58844b6eeb0479b4bad7fd570ff99980b9c935bc7ef3b00d93da5ccb535b4b",
          "sha1": "8ae536fa1aa4f5700ea08c1bff990f6e14a3b075",
          "md5": "011f35fd6c5825238e563667eda9986a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v159.7"
          }
        },
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v159.7"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "entity-v159.7.1.jar",
          "url": "entity-v159.7.1.jar",
          "size": 69564,
          "sha512": "73bc18fdcc4380afd55232391968f99bb621a5db8e1d382c0c19fb8303943528b3ad971a4efd9e200fb8dd0152545e994ad5a8a22b4693022a6ef4b665fc6001",
          "sha256": "3a58844b6eeb0479b4bad7fd570ff99980b9c935bc7ef3b00d93da5ccb535b4b",
          "sha1": "8ae536fa1aa4f5700ea08c1bff990f6e14a3b075",
          "md5": "011f35fd6c5825238e563667eda9986a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-v159.7.1-javadoc.jar",
          "url": "entity-v159.7.1-javadoc.jar",
          "size": 165657,
          "sha512": "415ec683a686bc7400b1519efc1bddc54c3217c82ab0c082e6fb152e6b91c40337ec27a2c9926cc321cde3e6b4809071ecbcb47081f1b124772f99612ca83d5d",
          "sha256": "874c19e64aed903dc8dbf1edc6d661aaf5d187859b9cd91b8d0997fea7c70ab3",
          "sha1": "7628fbc743210601f949d494eff38a0e82df603b",
          "md5": "a7355961f8483e37a9a795b3e5f88f94"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-v159.7.1-sources.jar",
          "url": "entity-v159.7.1-sources.jar",
          "size": 22800,
          "sha512": "512f2902d35fee4179ec6b462c46cdeb9cefe34e052d94336b93dc6d3dc3db220dbce0d2aa6b774be5ff0559de66d1a474c8f69b9342d518c7fdf99b7e4d43a5",
          "sha256": "91e591f8773fdc127ade25b63ff15922cc99f6c6de1f075347d12959cb6eda97",
          "sha1": "b830904dd69c53e80003ac72771bb426b3c8b04f",
          "md5": "c96ae57840b1e775941dc5a0b227084f"
        }
      ]
    }
  ]
}
